### ISSUE TITLE
Build prototype Grafana dashboard for analytics user interface

### ISSUE THREAD

**Issue by uzfarid** [k8-proxy/icap-monitoring-and-visualisation#23]

**Comment by uzfarid** [comment]
https://k8-proxy.github.io/analytics has sample metrics should be shown

**Comment by himanshu2464** [comment]
![image](https://user-images.githubusercontent.com/45463238/109210736-41c27580-77d3-11eb-8ffa-875b0044b8a3.png)

as per the metric to show on grafana dashboard i got the above metric from the Developer and according to that, i have built the prototype dashboard.

**Comment by uzfarid** [comment]
prototype must be based on what is shown in analytics ui
